name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/paints-by-numbers/paint-by-number
            git pull origin main
            cd frontend
            npm install
            npm run build
            sudo systemctl restart flask
            sudo systemctl restart nginx
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
